-- select * from customer limit 4

-- q1> what is total revenue generated by male vs female customer

select gender, sum(purchase_amount) as revenue
from customer
group by gender;

-- q2> which customer use discount but still spent more than the average purchase amount

select customer_id,purchase_amount
from customer
where discount_applied="Yes" and purchase_amount > (select avg(purchase_amount ) from customer);

-- q3> which are the top 5 products with the highest average review rating

select item_purchased,round(avg(review_rating),2) as average_review
from customer
group by item_purchased
order by average_review desc 
limit 5;

-- q4> compare the average purchase amount between standard and express shipping

select shipping_type,round(avg(purchase_amount),2) as shipping_type 
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;


-- q5> Do subscribed customer spend more? compare average spend and total revenue between subscriber and non subsciber

select subscription_status,
count(customer_id) as total_cutomer,
round(sum(purchase_amount),2) as total_revenue,
round(avg(purchase_amount),2) as avg_spend
from customer
group by subscription_status
order by total_revenue,avg(purchase_amount) desc;

-- q6> which five products have the highest percentage of purchases with discount applied

select item_purchased,
count((item_purchased)) as item_count
from customer
group by item_purchased 
order by item_count desc
limit 5;

-- q7> segment customer into new , returning, and loyal based on their total number of previous purchases, 
-- and show the count of each segement

with customer_type as (
select customer_id,previous_purchases,
case
	when previous_purchases=1 then 'New'
    when previous_purchases between 2 and 10 then 'Returning'
    else 'loyal'
    end as customer_segment
from customer
)
select customer_segment,count(*) as "Number of customer"
from customer_type
group by customer_segment;

-- q8> what are the top 3 most purchased products within each category

-- select category,item_purchased
-- from customer

-- q9> are customer who are repeat buyers (more than 5 previous purchase ) also likely to subscriber

select  subscription_status,
count(customer_id) as repate_buyers
from customer 
where previous_purchases > 5
group by subscription_status;

-- q10 > what is the revenue contribution of each age group

select age_group,
sum(purchase_amount) as revenue_by_age
from customer
group by age_group
order by revenue_by_age desc;
